.TH TASKASAUR 1 2021-01-22 
.SH NAME
taskasaur \- suckless kanban
.SH SYNOPSIS
.B taskasaur
[taskasaur options]
.SH DESCRIPTION
\fBtaskasaur\fP is a suckless style kanban program that runs on the command line with ncurses graphics. It stores data in the form of markdown for portability and readability.
.SH OPTIONS
.SH AUTHORS
\fBtaskasaur\fP was written by Daniel Liu
.SH REPORTING BUGS
Please open an issue at https://github.com/MrPicklePinosaur/taskasaur
